### ISSUE TITLE
[Question] Did you generate these code fully automaticly?

### ISSUE THREAD

**Issue by TheWayYouMakeMeFeel** [free5gc/openapi#1]
Hi guys,
	I'm gonna update these files to 3GPP R16 using openapi generator which version is 5.0.0-SNAPSHOT, but found that openapi generator cannot process well with enums which in you code it is perfect. At the same time, the struct member in your code has tags like json\bson\yaml\mapstructure, how can this happen? Did you use a better openapi generator or you code these features manually? Please tell me, thanks!

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

https://forum.free5gc.org/t/generating-openapi-models/437/3
