### ISSUE TITLE
openapi generator生成文件对应不上！！！

### ISSUE THREAD

**Issue by wvans123** [free5gc/openapi#33]
请问，R17对应的openapi.yaml可以共享出来吗？还有就是，对于R15的openapi.yaml进行修改后，使用openapi generator生成的go文件对应不上！！
请求帮助，急
@ianchen0119

**Comment by wvans123** [comment]
对于Nnrf_NFManagement的openapi.yaml，通过docker执行openapi-generator-cli（sudo docker run --rm -v $(pwd)/output:/local openapitools/openapi-generator-cli:v7.6.0 generate -i /local/openapi.yaml -g go -o /local/out），版本从v3.0.0尝试到最新版v7.6.0，其中v3.0.0-v3.3.4生成的文件与main中的文件差不多，但还是有不同；v4.0.0-v4.3.0均报错；v5.0.0以上就差距很大（可能是openapi版本问题）。

请问，可以帮忙解决这个问题吗，free5gc用的openapi generator是哪个版本呢？方便公开吗，开源的话，也方便大家进行一些修改~感谢！

**Comment by wvans123** [comment]
如果能够帮忙解答“修改哪些文件，执行什么操作之后，能够按自己的idea新增功能到free5gc的核心网中”，那将感激不尽！

**Comment by ianchen0119** [comment]
Hi @wvans123 

目前 free5GC 使用的 openapi generator 為團隊維護的客製版本，且暫時尚沒有公開的計畫。
如果你有貢獻 free5GC 的計畫，可以告訴我們需要使用的規格書和版本，由我們來產生對應的程式碼。

謝謝。

@andy89923 please follow up this GitHub issue, tks!

**Comment by wvans123** [comment]
hi，@ianchen0119 感谢回复

我们目前想要测试的是一些非3gpp协议中的功能，所以贡献的话，可能不适合贡献到free5GC，因为它是我们测试使用，不是R17 R18的标准内容，这点我估计你们也不会太使用？

**Comment by ianchen0119** [comment]
Hi @wvans123 

如果沒有貢獻 free5GC 的需要，可以參考 https://github.com/free5gc/ausf/pull/19 使用外部的 generator 產生需要的程式碼。

**Comment by wvans123** [comment]
好的，谢谢 @ianchen0119 
主要是我们的不是标准内容的功能，贡献上去估计是没意义的~ 总的来说还是感谢你的快速回复！ 祝free5gc越来越好
